# Generated by Django 4.0.4 on 2022-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_final_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration',
            field=models.IntegerField(default=24),
        ),
    ]
