# Generated by Django 4.0.4 on 2022-05-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('net_id', models.TextField()),
                ('student_id', models.TextField()),
                ('image', models.ImageField(blank=True, default='auction_images/default/default.svg', upload_to='team_images/')),
            ],
        ),
    ]
