# Generated by Django 4.0.4 on 2022-05-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_teammembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
