# Generated by Django 4.0.4 on 2022-05-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_teammembers_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
